version: 0.0
os: linux
files:
  - source: code
    destination: /opt/autotest_api

permissions:
  - object: /opt/autotest_api
    pattern: "**"
    owner: root
    group: root
    mode: 755
    type:
      - directory

hooks:
  BeforeInstall:
    - location: scripts/before_start.sh
      runas: root
  AfterInstall:
    - location: scripts/after_deploy.sh
      runas: root

  ValidateService:
    - location: scripts/validate.sh
      timeout: 10
      runas: root
